configs:
  # provider 0:阿里云 1:腾讯云 2:华为云
  - provider: 0
    name: "ali-PCM"
    accessid: ""
    accesssecret: ""
  - provider: 1
    name: "tencent-PCM"
    accessid: ""
    accesssecret: ""
  - provider: 2
    name: "huawei-PCM"
    accessid: ""
    accesssecret: ""
  - provider: 3
    name: "K8S-PCM"
    url: ""
    token: ""